### ISSUE TITLE
Add Elise to the team section

### ISSUE THREAD

**Issue by HeroicEric** [greenfieldhq/greenfieldhq.github.io#63]
ping @EliseFitz15 😄

**Comment by HeroicEric** [comment]
You'll want to add yourself to:
- Add yourself to https://github.com/greenfieldhq/greenfieldhq.github.io/blob/master/_data/authors.yml
- Add an image to https://github.com/greenfieldhq/greenfieldhq.github.io/tree/master/assets/images/team
- Add yourself to https://github.com/greenfieldhq/greenfieldhq.github.io/blob/master/_includes/about-us.html

**Comment by EliseFitz15** [comment]
Thanks @HeroicEric - Hoping to get to this later today or tomorrow. Should I add any headshot I have for now? Also any specific order to the .yml file or should I just throw my name at the end?

**Comment by HeroicEric** [comment]
@EliseFitz15 I don't think the order in the .yml matters for anything.

> Should I add any headshot I have for now?

I'd say yes, since it will probably be a while before we could set up something with the photographer again.

cc @mikepmunroe @rtremaine ^^

**Comment by mikepmunroe** [comment]
Agreed, if you have something you are happy with using now, please utilize
